### ISSUE TITLE
Release next version

### ISSUE THREAD

**Issue by Songmu** [tokuhirom/App-scan_prereqs_cpanfile#23]
Since the latest release on CPAN and the repository have diverged, could you release the next version?
@tokuhirom

**Comment by tokuhirom** [comment]
Added SONGMU to co-maintainers of App::scan_prereqs_cpanfile.
You can release it :)

**Comment by Songmu** [comment]
Thanks. Released as 1.10.

**Comment by alexcrack** [comment]
Please release new version with merged #25 feature
